### ISSUE TITLE
Really Appreciate your work and letting our fork just stay as its own thing

### ISSUE THREAD

**Issue by furtabs** [blueYOSHI9000/MarioPartyOverlay#2]
I did notice this comment 

Some ideas from a fork:

Option to hide certain games
Move greenscreen option next to background
Rename "In-game counters" to "Important counters"

**Comment by blueYOSHI9000** [comment]
I just thought some of your ideas were good so might as well add them (if I ever actually work on it lol).
And no worries, I don't see a reason to interfere with forks or anything. That's part of being open-sorce imo, anyone can take it and change it
